In [ ]:
import numpy as np

A = np.array([[1,1,-1],
              [-2,0,1],
              [5,-1,2],
              [2,6,-1]])
b = np.array([[2],
              [-2],
              [4],
              [5]])

Ab = np.hstack((A,b))
rankA = np.linalg.matrix_rank(A)
rankAb = np.linalg.matrix_rank(Ab)

print("rank A:",rankA)
print("rank Ab:",rankAb)
if rankA == rankAb:
    print("LGS möglich")
else:
    print("LGS nicht möglich")

rank A: 3
rank Ab: 4
LGS nicht möglich


In [ ]:
# Matrix A und Vektor b für ein System mit einer eindeutigen Lösung
A1 = np.array([[3, 2], [2, 1]])
b1 = np.array([8, 7])

# Lösung mit np.linalg.solve (eine eindeutige Lösung)
x1_solve = np.linalg.solve(A1, b1)
# Lösung mit np.linalg.lstsq (auch eindeutige Lösung)
x1_lstsq = np.linalg.lstsq(A1, b1, rcond=None)

print("Lösung mit np.linalg.solve für System 1:", x1_solve)
print("Lösung mit np.linalg.lstsq für System 1:", x1_lstsq)

# Matrix A und Vektor b für ein System mit unendlich vielen Lösungen
A2 = np.array([[2, 4], [1, 2]])  # Rangdefiziente Matrix
b2 = np.array([6, 3])

#x2_solve = np.linalg.solve(A2,b2)
# Lösung mit np.linalg.lstsq (liefert unendlich viele Lösungen)
x2_lstsq = np.linalg.lstsq(A2, b2, rcond=None)

#print("Lösung mit np.linalg.solve:", x2_solve)
print("Lösung mit np.linalg.lstsq für System 2:", x2_lstsq)



Lösung mit np.linalg.solve für System 1: [ 6. -5.]
Lösung mit np.linalg.lstsq für System 1: (array([ 6., -5.]), array([], dtype=float64), np.int32(2), array([4.23606798, 0.23606798]))
Lösung mit np.linalg.lstsq für System 2: (array([0.6, 1.2]), array([], dtype=float64), np.int32(1), array([5., 0.]))


In [3]:
import numpy as np
A = np.array([[2,-4,-2],[-5,1,1],[7,-5,-3]])
print(np.linalg.det(A))
print(np.linalg.matrix_rank(A))

-3.996802888650562e-15
2


[[ 2 -4 -2]
 [-5  1  1]
 [ 7 -5 -3]]
[[ 2 -5  7]
 [-4  1 -5]
 [-2  1 -3]]
