# Übung 5

## 1. Quadratisches LGS

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.array([
    [2, -5, 8],
    [-2, -7, 1],
    [4, 2, 7]
])

# Berechnung der Determinante mit np.linalg.det
det_A = np.linalg.det(A)

# Ausgabe der Determinante
print("Determinante der Koeffizientenmatrix A:", det_A)

# Überprüfung der Lösbarkeit
if np.isclose(det_A, 0):
    print("Das LGS hat unendlich viele Lösungen (Determinante = 0).")
else:
    print("Das LGS hat eine eindeutige Lösung (Determinante ≠ 0).")

Determinante der Koeffizientenmatrix A: 0.0
Das LGS hat unendlich viele Lösungen (Determinante = 0).


## 4. Projektion

In [7]:
# Vektoren definieren
a = np.array([1, 2])
v = np.array([-3, 4])

# Projektion berechnen
skalarprodukt = np.dot(a, v)
v_norm_squared = np.dot(v, v)
projektion = (skalarprodukt / v_norm_squared) * v

print("Orthogonale Projektion p:", projektion)

Orthogonale Projektion p: [-0.6  0.8]


## 5. PV-Ertrag

In [14]:
# Eingangsdaten
n = np.array([5, -5, 7])  # Normalenvektor der PV-Module
s = np.array([-10, 1, -5])  # Sonnenstrahlungsvektor

# 1. Orthogonale Projektion berechnen
s_dot_n = np.dot(s, n)
n_dot_n = np.dot(n, n)
s_proj = (s_dot_n / n_dot_n) * n

# 2. Leistungsanteil berechnen (immer positiv)
norm_s_proj = np.linalg.norm(s_proj)
norm_s = np.linalg.norm(s)
leistungsanteil = norm_s_proj / norm_s  # = |cos(φ)|

# 3. Winkelberechnung (immer zwischen 0° und 90°)
cos_phi = abs(s_dot_n) / (norm_s * np.linalg.norm(n))  # Betrag des Cosinus
phi_rad = np.arccos(cos_phi)
phi_deg = np.degrees(phi_rad)

# Ausgabe der Ergebnisse
print("Orthogonale Projektion von s auf n:")
print(s_proj)
print("\nAnteil der aufgenommenen Strahlungsleistung:", round(leistungsanteil, 4), 
      f"({round(leistungsanteil*100, 2)}%)")
print("\nEffektiver Winkel zwischen n und s:", round(phi_deg, 2), "Grad")
print("cos(φ):", round(cos_phi, 4))

Orthogonale Projektion von s auf n:
[-4.54545455  4.54545455 -6.36363636]

Anteil der aufgenommenen Strahlungsleistung: 0.8058 (80.58%)

Effektiver Winkel zwischen n und s: 36.31 Grad
cos(φ): 0.8058


Der Kosinus des Winkels φ zwischen dem Normalenvektor der PV-Module (n) und dem Sonnenstrahlungsvektor (s) bestimmt direkt, wie viel der einfallenden Strahlungsleistung tatsächlich von den Modulen genutzt wird.

## 6. Leontief Modell

### 1.

In [15]:
import numpy as np

A = np.array([
    [0.2, 0.3, 0.4],
    [0.4, 0.4, 0.1],
    [0.5, 0.1, 0.3]
])

d = np.array([4, 2, 3])
I = np.eye(3)  # Einheitsmatrix

# Technologiematrix berechnen
I_minus_A = I - A

# Produktionsplan p lösen
p = np.linalg.solve(I_minus_A, d)

print("Produktionsplan p:")
print(np.round(p, 2))

Produktionsplan p:
[31.72 29.68 31.18]


### 2.

In [16]:
inv_I_minus_A = np.linalg.inv(I_minus_A)

print("Inverse (I - A)^{-1}:")
print(np.round(inv_I_minus_A, 2))

# Prüfe auf Nicht-Negativität
is_non_negative = np.all(inv_I_minus_A >= 0)
print("\nIst (I - A)^{-1} nicht-negativ?", is_non_negative)

Inverse (I - A)^{-1}:
[[4.41 2.69 2.9 ]
 [3.55 3.87 2.58]
 [3.66 2.47 3.87]]

Ist (I - A)^{-1} nicht-negativ? True


### 3.

In [17]:
B = np.array([
    [0.9, 0.3, 0.4],  # Chemieverbrauch stark erhöht
    [0.4, 0.4, 0.1],
    [0.5, 0.1, 0.3]
])

I_minus_B = I - B
try:
    p_new = np.linalg.solve(I_minus_B, d)
    print("Produktionsplan mit B:", np.round(p_new, 2))
except np.linalg.LinAlgError:
    print("Matrix (I - B) ist singulär (nicht invertierbar).")

# Alternative: Berechne (I - B)^{-1} (falls möglich)
try:
    inv_I_minus_B = np.linalg.inv(I_minus_B)
    print("\nInverse (I - B)^{-1}:")
    print(np.round(inv_I_minus_B, 2))
except:
    print("Inverse existiert nicht.")

Produktionsplan mit B: [-15.21  -8.09  -7.73]

Inverse (I - B)^{-1}:
[[-2.11 -1.29 -1.39]
 [-1.7   0.67 -0.88]
 [-1.75 -0.82  0.31]]
