# Übung 4

## 1. Rang

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.array([[1, 0, -1, 1],
              [2, 3, 1, 5],
              [3, 2, -1, 6],
              [0, 5, 5, 5]])

rang = np.linalg.matrix_rank(A)
print("Der Rang von A ist:", rang)

Der Rang von A ist: 3


## 2. Diät

Die Formel für die Cambridge-Diät, eine beliebte Diät in den 1980er Jahren, basiert auf jahrelanger
Forschung. Um die gewünschten Mengen und Verhältnisse der Nährstoffe zu erreichen, musste man
eine Vielfalt von Lebensmitteln einbeziehen. Jedes Lebensmittel liefert mehrere der erforderlichen
Inhaltsstoffe, jedoch nicht in den genau richtigen Anteilen. So war zum Beispiel fettfreie Milch
eine wichtige Eiweißquelle, enthielt aber zu viel Kalzium. Daher wurde Sojamehl für einen Teil des
Eiweißes verwendet, da Sojamehl wenig Kalzium enthält. Allerdings enthält Sojamehl zu viel Fett, so
dass Molke hinzugefügt wurde, da sie im Verhältnis zum Kalzium weniger Fett liefert. Leider enthält
die Molke zu viele Kohlenhydrate … Das folgende Beispiel veranschaulicht das Problem in kleinem
Maßstab. In der Tabelle Tabelle 1 sind drei der Bestandteile der Diät aufgeführt, zusammen mit den
Mengen bestimmter Nährstoffe.

PYTHON: Wenn möglich, finden Sie eine Kombination aus fettfreier Milch, Sojamehl und Molke,
um die geforderten Mengen an Eiweiß, Kohlenhydraten und Fett zu erhalten.


In [11]:
import numpy as np

# Matrix A und Vektor b
A = np.array([[36, 51, 13],
              [52, 34, 74],
              [0, 7, 1.1]])

b = np.array([33, 45, 3])

# Lösen des Gleichungssystems
x = np.linalg.solve(A, b)
print(x,"\n")

# Umrechnung in Gramm (da die Tabelle pro 100 g angegeben ist)
x_grams = x * 100
print(x_grams,"\n")
# Ausgabe der Lösung in Gramm
print("Die benötigten Mengen sind:")
print(f"fettfreie Milch: {x_grams[0]:.1f} g")
print(f"Sojamehl: {x_grams[1]:.1f} g")
print(f"Molke: {x_grams[2]:.1f} g")

[0.27722318 0.39192086 0.23323088] 

[27.72231836 39.19208616 23.32308805] 

Die benötigten Mengen sind:
fettfreie Milch: 27.7 g
Sojamehl: 39.2 g
Molke: 23.3 g


## Ill-Conditioned Linear System 

In [14]:
A = np.array([[0.835, 0.667],
              [0.333, 0.266]])

b1 = np.array([0.168, 0.067])
b2 = np.array([0.168, 0.066])

Ab1 = np.column_stack((A, b1))
Ab2 = np.column_stack((A, b2))
# Rang der Koeffizientenmatrix A
rank_A = np.linalg.matrix_rank(A)

# Rang der erweiterten Koeffizientenmatrix (A|b)
rank_Ab1 = np.linalg.matrix_rank(Ab1)
rank_Ab2 = np.linalg.matrix_rank(Ab2)

if rank_A == rank_Ab1:
    if rank_A == A.shape[1]:  # Unique solution
        solution = np.linalg.solve(A, b1)
        print("Unique solution:", solution)
    else:  # Infinitely many solutions
        print("Infinitely many solutions.")
else:
    print("No solution. The system is inconsistent.")

if rank_A == rank_Ab2:
    if rank_A == A.shape[1]:  # Unique solution
        solution = np.linalg.solve(A, b2)
        print("Unique solution:", solution)
    else:  # Infinitely many solutions
        print("Infinitely many solutions.")
else:
    print("No solution. The system is inconsistent.")


Unique solution: [ 1. -1.]
Unique solution: [-665.99999998  833.99999998]


## Rechnen mit Matrizen

In [30]:
A = np.array([[1,-2,3],
              [0,-5,4],
              [4,-3,8]])
B = np.array([[1,2],
              [0,4],
              [3,7]])
c = np.array([[1],[2],[3]])

AxB = np.dot(A,B)
print(AxB,"\n")

try:
    BxA = np.dot(B, A)
    print(BxA)
except ValueError as e:
    print("BxA ist nicht wohldefiniert:", e)
    print("\n")

BT = B.T
BTxA = np.dot(BT,A)
print(BTxA,"\n")

cT = c.T
cTxB = np.dot(cT,B)
print(cTxB,"\n")

cTxBBTAc = np.dot((np.dot(cT,((np.dot(B,BT))+A))),c)
print(cTxBBTAc,"\n")

[[10 15]
 [12  8]
 [28 52]] 

BxA ist nicht wohldefiniert: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)


[[ 13 -11  27]
 [ 30 -45  78]] 

[[10 31]] 

[[1137]] 



## 5. Adjazenz-Matrix

In [34]:
Flugmatrix=np.array([[0,0,1,0,1],
                    [1,0,0,0,1],
                    [0,0,0,1,1],
                    [0,1,0,0,1],
                    [1,1,1,1,0]])

print("Adjazenz-Matrix:\n",Flugmatrix)

Adjazenz-Matrix:
 [[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]


In [35]:
# 1. Berechnung von C^2 (genau ein Umstieg)
C_squared = np.linalg.matrix_power(Flugmatrix, 2)
print("\nC^2 (genau ein Umstieg):")
print(C_squared)

# 2. Berechnung von C^3 (genau zwei Umstiege)
C_cubed = np.linalg.matrix_power(Flugmatrix, 3)
print("\nC^3 (genau zwei Umstiege):")
print(C_cubed)

# 3. Berechnung von C + C^2 + C^3 (maximal zwei Umstiege)
C_total = Flugmatrix + C_squared + C_cubed
print("\nC + C^2 + C^3 (maximal zwei Umstiege):")
print(C_total)


C^2 (genau ein Umstieg):
[[1 1 1 2 1]
 [1 1 2 1 1]
 [1 2 1 1 1]
 [2 1 1 1 1]
 [1 1 1 1 4]]

C^3 (genau zwei Umstiege):
[[2 3 2 2 5]
 [2 2 2 3 5]
 [3 2 2 2 5]
 [2 2 3 2 5]
 [5 5 5 5 4]]

C + C^2 + C^3 (maximal zwei Umstiege):
[[3 4 4 4 7]
 [4 3 4 4 7]
 [4 4 3 4 7]
 [4 4 4 3 7]
 [7 7 7 7 8]]
